import { PDFDocument, StandardFonts, rgb, PageSizes, type PDFFont, type Color } from "pdf-lib";
import { formatCentsExact } from "@/lib/company/format";
import { toWinAnsiSafe, wrapText } from "@/lib/invoices/pdfModel";
import type { InvestorKpis } from "./collect";
import { formatRunwayVerdict } from "./narrative";

/** Same word-wrap width as the invoices PDF model (spec §5) — a fixed char
 *  count, not a measured font metric, so the model stays pure/deterministic;
 *  `renderInvestorReportPdf` does the pixel-accurate measuring, only for
 *  right-aligning the KPI values. */
const WRAP_WIDTH = 90;

/** Everything `renderInvestorReportPdf` needs to paint the one-page (or
 *  more, for a long narrative) investor update, with every formatting
 *  decision already made — spec §5, verbatim. */
export type InvestorReportModel = {
  banner: "SIMULATED NARRATIVE" | null;
  header: { orgName: string; title: string; periodLabel: string };
  kpiGrid: Array<[label: string, value: string]>;
  narrative: string[][];
  footer: string;
};

/** "$X (N)" — dollars plus a parenthetical count, both already WinAnsi/format
 *  safe individually; used for the receivables and issued-invoices rows. */
function formatMoneyWithCount(cents: number, count: number): string {
  return `${formatCentsExact(cents)} (${count})`;
}

/** "12 (8H / 3W / 1R)" when a health mix exists, otherwise just the plain
 *  total — omitting the mix entirely (not rendering zeros) when the org has
 *  no health snapshots at all, same "absent, don't fake it" rationale as
 *  `formatHealthMixClause` in narrative.ts. */
function formatCustomersValue(customers: InvestorKpis["customers"]): string {
  if (!customers.healthMix) return String(customers.total);
  const { healthy, watch, at_risk } = customers.healthMix;
  return `${customers.total} (${healthy}H / ${watch}W / ${at_risk}R)`;
}

/**
 * Builds the pure, print-ready report model (spec §5). `paragraphs` is
 * whatever `generateInvestorNarrative` produced (real or simulated — this
 * function doesn't care which, only `simulated` controls the banner). Every
 * string is passed through the exported `toWinAnsiSafe` — reused verbatim
 * from `src/lib/invoices/pdfModel.ts`, not duplicated — so a CJK/emoji org
 * name or AI-written narrative can never crash pdf-lib's WinAnsi encoder
 * (same review finding slice 28 already fixed once for invoices). Narrative
 * paragraphs are sanitized BEFORE `wrapText` so the hard-splitter never cuts
 * a surrogate pair in half. `now` is injected so the footer date is
 * deterministic under test.
 */
export function buildInvestorReportModel(
  kpis: InvestorKpis,
  paragraphs: string[],
  simulated: boolean,
  now: Date,
): InvestorReportModel {
  const rawGrid: Array<[string, string]> = [
    ["Revenue (latest month)", formatCentsExact(kpis.revenue.latestCents)],
    ["Profit (latest month)", formatCentsExact(kpis.profit.latestCents)],
    ["Outstanding receivables", formatMoneyWithCount(kpis.receivables.totalCents, kpis.receivables.count)],
    ["Overdue", formatCentsExact(kpis.receivables.overdueCents)],
    ["Runway", formatRunwayVerdict(kpis.runway)],
    [
      "Invoices issued this period",
      formatMoneyWithCount(kpis.invoicing.issuedCents, kpis.invoicing.issuedCount),
    ],
    ["Collected this period", formatCentsExact(kpis.invoicing.collectedCents)],
    ["Customers", formatCustomersValue(kpis.customers)],
  ];

  return {
    banner: simulated ? "SIMULATED NARRATIVE" : null,
    header: {
      orgName: toWinAnsiSafe(kpis.orgName),
      title: "Investor Update",
      periodLabel: toWinAnsiSafe(kpis.periodLabel),
    },
    kpiGrid: rawGrid.map(([label, value]) => [toWinAnsiSafe(label), toWinAnsiSafe(value)]),
    narrative: paragraphs.map((p) => wrapText(toWinAnsiSafe(p), WRAP_WIDTH)),
    footer: toWinAnsiSafe(`Generated by iDesign Command Center — ${now.toISOString().slice(0, 10)}`),
  };
}

const [PAGE_WIDTH, PAGE_HEIGHT] = PageSizes.Letter;
const MARGIN = 50;
// Same y-cursor floor rationale as pdfRender.ts: once the cursor crosses
// below this, force a page break before drawing the next row.
const BOTTOM_LIMIT = 70;
const RIGHT_EDGE = PAGE_WIDTH - MARGIN; // 562 on Letter — spec §5's KPI value right-alignment x.

const BLACK: Color = rgb(0, 0, 0);
const GRAY: Color = rgb(0.45, 0.45, 0.45);
const LIGHT_GRAY: Color = rgb(0.82, 0.82, 0.82);

/**
 * Paints an `InvestorReportModel` onto a Letter-size PDF with pdf-lib (spec
 * §5) — a pure painter mirroring `src/lib/invoices/pdfRender.ts`'s
 * conventions exactly (Letter, margin 50, Helvetica/Bold via StandardFonts,
 * y-cursor with a page-break helper, banner as large light-gray horizontal
 * text). Every formatting decision was already made by
 * `buildInvestorReportModel`; this only lays it out and turns the page when
 * the cursor runs out of room. The footer is drawn once, at the bottom
 * margin of whichever page ends up last (a long narrative may spill to page
 * 2+; the footer follows it there, same as the invoices painter).
 */
export async function renderInvestorReportPdf(model: InvestorReportModel): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  let page = pdfDoc.addPage(PageSizes.Letter);
  let y = PAGE_HEIGHT - MARGIN;

  function newPage(): void {
    page = pdfDoc.addPage(PageSizes.Letter);
    y = PAGE_HEIGHT - MARGIN;
  }

  function ensureSpace(): void {
    if (y < BOTTOM_LIMIT) newPage();
  }

  function drawLeftText(text: string, x: number, size: number, f: PDFFont, color: Color = BLACK): void {
    page.drawText(text, { x, y, size, font: f, color });
  }

  // Right-aligns `text` so it ends at `rightX`, measuring width with the
  // real font/size pair — same trick pdfRender.ts uses for invoice totals.
  function drawRightText(text: string, rightX: number, size: number, f: PDFFont, color: Color = BLACK): void {
    const width = f.widthOfTextAtSize(text, size);
    page.drawText(text, { x: rightX - width, y, size, font: f, color });
  }

  // --- Banner --------------------------------------------------------
  // Deliberately horizontal, not rotated — same rationale as the invoices
  // DRAFT/VOID banner (pdfRender.ts): a purely cosmetic honesty signal that
  // doesn't need rotation-origin math.
  if (model.banner) {
    drawLeftText(model.banner, MARGIN, 36, fontBold, LIGHT_GRAY);
    y -= 40;
  }

  // --- Header ----------------------------------------------------------
  drawLeftText(model.header.orgName, MARGIN, 18, fontBold);
  y -= 22;
  drawLeftText(model.header.title, MARGIN, 14, font);
  y -= 18;
  drawLeftText(model.header.periodLabel, MARGIN, 11, font, GRAY);
  y -= 26;

  // --- KPI grid (two columns; values right-aligned to RIGHT_EDGE) ------
  for (const [label, value] of model.kpiGrid) {
    ensureSpace();
    drawLeftText(label, MARGIN, 10, font);
    drawRightText(value, RIGHT_EDGE, 10, fontBold);
    y -= 16;
  }
  y -= 14;

  // --- Narrative ---------------------------------------------------------
  ensureSpace();
  drawLeftText("Narrative", MARGIN, 9, fontBold, GRAY);
  y -= 16;
  for (const paragraph of model.narrative) {
    for (const line of paragraph) {
      ensureSpace();
      drawLeftText(line, MARGIN, 10, font);
      y -= 13;
    }
    y -= 10; // blank-line gap between paragraphs
  }

  // --- Footer --------------------------------------------------------
  // Fixed position at the bottom margin of whichever page ended up last —
  // independent of the content cursor above, same convention as
  // pdfRender.ts's invoice footer.
  page.drawText(model.footer, { x: MARGIN, y: MARGIN - 20, size: 8, font, color: GRAY });

  return pdfDoc.save();
}
